name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Test with pytest
        run: |
          python -m pip install -e '.[test]'
          pytest
      - name: Install Python Package Dependencies
        run: |
          python3 -m pip -U pip build wheel
          python3 -m pip install -r requirements.txt
      - name: Build Python Package
        run: python3 -m build
      - name: Publish Python Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
        # run: twine upload --repository pypi dist/* --verbose
