---
on: [push, pull_request]

jobs:
  build:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - 
        name: Run Pylint
        env:
          REPORT_ONLY: true
          SHOW_ERRORS: true
        run: bash scripts/pylint_script.sh
